name: Comment on fork PRs

permissions:
  contents: write


on:
  pull_request_target:
    types: [opened, reopened, synchronize, labeled]

# Cancel any existing runs of this workflow on the same branch/pr
# We always want to build/deploy/test a new commit over an older one
concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: true

jobs:
  # Looks for labels like "deploy-to-<env>" attached to a PR so we can deploy to those envs
  get-deploy-labels:
    runs-on: mdb-dev
    if: github.event.pull_request.head.repo.fork
    outputs:
      deploy-envs: ${{ steps.get-labels.outputs.deploy-envs }}
    steps:
      - name: Pull MindsDB Github Actions
        uses: actions/checkout@v4
        with:
          repository: mindsdb/github-actions
          path: github-actions
      - id: get-labels
        uses: ./github-actions/get-deploy-labels

  comment:
    runs-on: mdb-dev
    needs: [get-deploy-labels]
    if: needs.get-deploy-labels.outputs.deploy-envs != '[]' && github.event.pull_request.head.repo.fork
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Test!'
            })
