name: Deploy fork PR to dev

permissions:
  pull-requests: write
  repository-projects: write

# This workflow is only run for PRs from forks
# The workflow_run trigger means this runs after build-deploy-dev, and after
# any docker building is done on the fork branch.defaults:
# Using this trigger means we have access to secrets. But we should be careful
# as the forked code is still untrusted code.
on:
  workflow_run:
    workflows: ["Build and deploy to dev"]
    types:
      - completed

# Cancel any existing runs of this workflow on the same branch/pr
# We always want to build/deploy/test a new commit over an older one
concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: true

jobs:
  # Looks for labels like "deploy-to-<env>" attached to a PR so we can deploy to those envs
  get-deploy-labels:
    if: github.event.pull_request.head.repo.fork
    runs-on: mdb-dev
    outputs:
      deploy-envs: ${{ steps.get-labels.outputs.deploy-envs }}
    steps:
      - name: Pull MindsDB Github Actions
        uses: actions/checkout@v4
        with:
          repository: mindsdb/github-actions
          path: github-actions
      - id: get-labels
        uses: ./github-actions/get-deploy-labels
  
  # Call our deployment workflow with the forked PRs image tag
  deploy:
    name: Deploy
    needs: [get-deploy-labels]
    if: needs.get-deploy-labels.outputs.deploy-envs != '[]'
    uses: ./.github/workflows/deploy.yml
    with:
      deploy-envs: ${{ needs.get-deploy-labels.outputs.deploy-envs }}
      image-tag: ${{ github.event.workflow_run.head_sha }}
    secrets: inherit

  # Run integration tests
  # TODO: Run these against the deployed environment
  run_tests:
    name: Run Integration Tests
    needs: [deploy]
    uses: ./.github/workflows/test_on_deploy.yml
    secrets: inherit
